### ISSUE TITLE
TryMutex<T> should have Send bound on T

### ISSUE THREAD

**Issue by ammaraskar** [Noctune/try-mutex#2]
Hi there, we (Rust group @sslab-gatech) are scanning crates on crates.io for potential soundness bugs. We noticed that `TryMutex` implements `Sync` for all types `T`:

https://github.com/mpdn/try-mutex/blob/9775aef4516135958fa428ce08b346325c0493f3/src/lib.rs#L127

This should probably be bounded by `T: Send` just like the standard library's [Mutex](https://doc.rust-lang.org/std/sync/struct.Mutex.html#impl-Sync), otherwise it allows smuggling non-Send types like `Rc` across thread-boundaries like so:

```rust
#![forbid(unsafe_code)]

use try_mutex::TryMutex;

use std::rc::Rc;
use crossbeam_utils::thread;

fn main() {
    let rc = Rc::new(());
    let rc_clone = rc.clone();

    let try_mutex = TryMutex::new(rc_clone);
    thread::scope(|s| {    
        s.spawn(|_| {
            let smuggled_rc = try_mutex.try_lock().unwrap();
            println!("RC in thread: {:p}", *smuggled_rc);
        });
    });
    println!("RC in main:   {:p}", rc);
}
```

This outputs:
```
RC in thread: 0x5642ef5ffa50
RC in main:   0x5642ef5ffa50
```

and can lead to data races from safe Rust code.

**Comment by mpdn** [comment]
Yup, looks like a soundness issue.

Fixed via https://github.com/mpdn/try-mutex/commit/d2691fd28b1149815bc1e3f8c9e527956a745bec and new 0.3 package.

Thanks.
